[economy]
T = 40
uncertain_T = 4
beta = 0.96
gamma = 0.9
B = 2.0
relax = 0.01
borrowing_limit = 0.0
a_min = 0.0
a_max = 5.0
n_a = 300
curvature = 2.0
rmin = -0.05
rmax = 0.045

[solver]
maxit = 1000
tol = 1e-6
root_node_index = 1
stationary_node_index = -1
checkpoint_every_secs = 300

[[aggregate_states]]
name = "Normal"
z_states = [0.5, 0.05]
Pz = [[0.9, 0.1], [0.5, 0.5]]

[[aggregate_states]]
name = "Recession"
z_states = [0.3, 0.05]
Pz = [[0.6, 0.4], [0.2, 0.8]]

[aggregate_transition]
Pagg = [[0.8, 0.2], [0.5, 0.5]]
